/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pmodul8;
import java.awt.Image;
import java.awt.image;
import javax.swing.*;
import java.io.*;
import javax.swing.filechooser.FileFilter;


/**
 *
 * @author Lenovo
 */
public class fGambar extends javax.swing.JFrame {
    DefaultListModel gambar;
    
    
    final String[] EXT= {".jpg",".jpeg",".gift", ".tiff", ".png"};

    /**
     * Creates new form fGambar
     */
    public fGambar() {
        initComponents();
        gambar=new DefaultListModel();
        lstDaftar.setModel(gambar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnpilih = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstdaftar = new javax.swing.JList<>();
        chkfit = new javax.swing.JCheckBox();
        jScrollPane = new javax.swing.JScrollPane();
        lblgambar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnpilih.setText("Pilih Gambar");
        btnpilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpilihActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus Pilihan");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        lstdaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstdaftarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstdaftar);

        chkfit.setText("Fit Lebar Frame Gambar");

        jScrollPane.setViewportView(lblgambar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnpilih)
                        .addGap(71, 71, 71)
                        .addComponent(btnhapus)
                        .addGap(44, 44, 44)
                        .addComponent(chkfit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpilih)
                    .addComponent(btnhapus)
                    .addComponent(chkfit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpilihActionPerformed
        // TODO add your handling code here:
        JfileChooser fc= new JfileChooser();
        fc.addChoosableFileFilter(new jenisFile(EXT));
        int hasil=fc.showOpenDialog(this);
        if(hasil==JfileChooser.APPROVE_OPTION) {
            File file=fc.getSelectedFile();
            String nf=file.getAbsolutePath();
            gambar.addElement(nf);
        }
    }//GEN-LAST:event_btnpilihActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        int index=lstDaftar.getSelectedIndex();
        gambar.remove(index);
        lblGambar.setIcon(null);
    }//GEN-LAST:event_btnhapusActionPerformed

    private void lstdaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstdaftarMouseClicked
        // TODO add your handling code here:
        String nf=lstDaftar.getSelectedValue().toString();
        Imagelcon gbr=new imagelcon(nf);
        if(chkFit.isSelected())
            gbr=new Imagelcon(gbr.getImage().getScaledInstance(200,-1,Image.SCALE_DEFAULT));
        lblgambar.setIcon(gbr);
    }//GEN-LAST:event_lstdaftarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fGambar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnpilih;
    private javax.swing.JCheckBox chkfit;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblgambar;
    private javax.swing.JList<String> lstdaftar;
    // End of variables declaration//GEN-END:variables
}
