/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas1;

/**
 *
 * @author ACER
 */
public class Tugas1Design extends javax.swing.JFrame {

    /**
     * Creates new form Tugas1Design
     */
    public Tugas1Design() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        SeksGrup006 = new javax.swing.ButtonGroup();
        lblNamaPegawai006 = new javax.swing.JLabel();
        lblGajiPokok006 = new javax.swing.JLabel();
        lblSeks006 = new javax.swing.JLabel();
        lblStatus006 = new javax.swing.JLabel();
        txtNamaPegawai006 = new javax.swing.JTextField();
        txtGajiPokok006 = new javax.swing.JTextField();
        txtGajiTotal006 = new javax.swing.JTextField();
        txtPasangan006 = new javax.swing.JTextField();
        rbPria006 = new javax.swing.JRadioButton();
        rbWanita006 = new javax.swing.JRadioButton();
        cbMenikah006 = new javax.swing.JCheckBox();
        lblJumlahAnak006 = new javax.swing.JLabel();
        txtJumlahAnak006 = new javax.swing.JTextField();
        lblPasangan006 = new javax.swing.JLabel();
        lblGajiTotal006 = new javax.swing.JLabel();
        btnHitung006 = new javax.swing.JButton();
        btnHapus006 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblNamaPegawai006.setText("Nama Pegawai");

        lblGajiPokok006.setText("Gaji Pokok");

        lblSeks006.setText("Seks");

        lblStatus006.setText("Status");

        txtGajiTotal006.setEditable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, SeksGrup006, org.jdesktop.beansbinding.ELProperty.create("${selection.enabled}"), txtPasangan006, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        SeksGrup006.add(rbPria006);
        rbPria006.setText("Pria");
        rbPria006.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPria006ActionPerformed(evt);
            }
        });

        SeksGrup006.add(rbWanita006);
        rbWanita006.setText("Wanita");
        rbWanita006.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbWanita006ActionPerformed(evt);
            }
        });

        cbMenikah006.setText("Menikah");
        cbMenikah006.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMenikah006ActionPerformed(evt);
            }
        });

        lblJumlahAnak006.setText("Jumlah Anak");

        txtJumlahAnak006.setEnabled(false);

        lblGajiTotal006.setText("Gaji Total");

        btnHitung006.setText("Hitung Gaji Total");
        btnHitung006.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitung006ActionPerformed(evt);
            }
        });

        btnHapus006.setText("Hapus");
        btnHapus006.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus006ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNamaPegawai006)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNamaPegawai006, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblGajiPokok006)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rbPria006)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rbWanita006))
                                        .addComponent(txtGajiPokok006, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbMenikah006))))
                            .addComponent(btnHitung006)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSeks006)
                                            .addComponent(lblStatus006))
                                        .addGap(44, 44, 44))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblPasangan006)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(lblJumlahAnak006)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtJumlahAnak006, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                                    .addComponent(txtPasangan006))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGajiTotal006)
                        .addGap(18, 18, 18)
                        .addComponent(txtGajiTotal006, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(btnHapus006, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaPegawai006)
                    .addComponent(txtNamaPegawai006, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGajiPokok006)
                    .addComponent(txtGajiPokok006, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeks006)
                    .addComponent(rbPria006)
                    .addComponent(rbWanita006))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus006)
                    .addComponent(cbMenikah006))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlahAnak006)
                    .addComponent(txtJumlahAnak006, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPasangan006, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPasangan006))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHitung006)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGajiTotal006)
                    .addComponent(txtGajiTotal006, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHapus006, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbPria006ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPria006ActionPerformed
        if (rbPria006.isSelected()) {
            lblPasangan006.setText("Nama Istri");
        }
            
    }//GEN-LAST:event_rbPria006ActionPerformed

    private void rbWanita006ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbWanita006ActionPerformed
        if (rbWanita006.isSelected()) {
            lblPasangan006.setText("Nama Suami");
        }
    }//GEN-LAST:event_rbWanita006ActionPerformed

    private void cbMenikah006ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMenikah006ActionPerformed
        if (cbMenikah006.isSelected()) {
            txtJumlahAnak006.setEnabled((true));
        } else {
            txtJumlahAnak006.setEnabled((false));
            txtJumlahAnak006.setText("0");
        }
    }//GEN-LAST:event_cbMenikah006ActionPerformed

    private void btnHitung006ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitung006ActionPerformed
                      int gajiPokok = Integer.parseInt(txtGajiPokok006.getText());
                int jumlahAnak = Integer.parseInt(txtJumlahAnak006.getText());
                double gajiTotal;

                if (jumlahAnak >= 3) {
                    gajiTotal = gajiPokok + (gajiPokok * 0.10 * 3);
                } else {
                    gajiTotal = gajiPokok + (gajiPokok * 0.10 * jumlahAnak);
                }

                txtGajiTotal006.setText(String.valueOf(gajiTotal));
            
    }//GEN-LAST:event_btnHitung006ActionPerformed

    private void btnHapus006ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus006ActionPerformed
        txtNamaPegawai006.setText("");
        txtGajiPokok006.setText("");
        SeksGrup006.clearSelection();
        cbMenikah006.setSelected(false);
        lblPasangan006.setText("");
        txtJumlahAnak006.setText("");
        txtPasangan006.setText("");
        txtGajiTotal006.setText("");
    }//GEN-LAST:event_btnHapus006ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup SeksGrup006;
    private javax.swing.JButton btnHapus006;
    private javax.swing.JButton btnHitung006;
    private javax.swing.JCheckBox cbMenikah006;
    private javax.swing.JLabel lblGajiPokok006;
    private javax.swing.JLabel lblGajiTotal006;
    private javax.swing.JLabel lblJumlahAnak006;
    private javax.swing.JLabel lblNamaPegawai006;
    private javax.swing.JLabel lblPasangan006;
    private javax.swing.JLabel lblSeks006;
    private javax.swing.JLabel lblStatus006;
    private javax.swing.JRadioButton rbPria006;
    private javax.swing.JRadioButton rbWanita006;
    private javax.swing.JTextField txtGajiPokok006;
    private javax.swing.JTextField txtGajiTotal006;
    private javax.swing.JTextField txtJumlahAnak006;
    private javax.swing.JTextField txtNamaPegawai006;
    private javax.swing.JTextField txtPasangan006;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
