/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pmodul4;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class fDialog extends javax.swing.JFrame {

    /**
     * Creates new form fDialog
     */
    public fDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnok = new javax.swing.JButton();
        btnerror = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnYN = new javax.swing.JButton();
        btnYNC = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btncustom = new javax.swing.JButton();
        btnpilihlist = new javax.swing.JButton();
        btnpilihisi = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnok.setText("OK Dialog");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        btnerror.setText("Error Dialog");
        btnerror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnerrorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnerror)
                    .addComponent(btnok))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnok)
                .addGap(44, 44, 44)
                .addComponent(btnerror)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Simple Dialog", jPanel1);

        btnYN.setText("YES/NO Konfirmasi");
        btnYN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYNActionPerformed(evt);
            }
        });

        btnYNC.setText("YES/NO/Cancel Konfirmasi");
        btnYNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYNCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(btnYN)
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnYNC)
                .addGap(96, 96, 96))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnYN)
                .addGap(50, 50, 50)
                .addComponent(btnYNC)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Konfirmasi Dialog", jPanel2);

        btncustom.setText("Custom YES/NO/CANCEL");
        btncustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncustomActionPerformed(evt);
            }
        });

        btnpilihlist.setText("Pilihan List");
        btnpilihlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpilihlistActionPerformed(evt);
            }
        });

        btnpilihisi.setText("Pilihan Isian");
        btnpilihisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpilihisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(btncustom)
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpilihisi)
                    .addComponent(btnpilihlist))
                .addGap(126, 126, 126))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btncustom)
                .addGap(18, 18, 18)
                .addComponent(btnpilihlist)
                .addGap(18, 18, 18)
                .addComponent(btnpilihisi)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Option Dialog", jPanel3);

        btnkeluar.setText("KELUAR");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(btnkeluar)))
                .addContainerGap(638, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnkeluar)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Mudahnya Belajar JAva");
    }//GEN-LAST:event_btnokActionPerformed

    private void btnerrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnerrorActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
                "Belajar Java Harus Serius",
                "Peringatan",
                JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnerrorActionPerformed

    private void btnYNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYNActionPerformed
        // TODO add your handling code here:
        int jwb =JOptionPane.showConfirmDialog(this,
                "Belajar Java Itu Mudah\nSetujukah Anda?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        if(jwb==0)
                JOptionPane.showMessageDialog(this,
                        "Anda Memilih YES");
        else
        JOptionPane.showMessageDialog(this,
                "NO adalah pilihan anda");
    }//GEN-LAST:event_btnYNActionPerformed

    private void btnYNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYNCActionPerformed
        // TODO add your handling code here:
        int jwb = JOptionPane.showConfirmDialog(this,
                "Akan menghapus data"+"\nanda yakin?",
                "konfirmasi",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        switch (jwb){
            case 0:JOptionPane.showMessageDialog(this, "Jawab YeS");
            break;
            case 1:JOptionPane.showMessageDialog(this, "Jawab NO");
            break;
            case 2:JOptionPane.showMessageDialog(this, "Jawab CANCEL");
            break;
            default:
                JOptionPane.showMessageDialog(this, "Koq Gak Jawab?");
                
            
        }
    }//GEN-LAST:event_btnYNCActionPerformed

    private void btncustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncustomActionPerformed
        // TODO add your handling code here:
        Object[]option={"Ya,Sip","Tidak,Trims","Kirim Saja!"};
        int jwb=JOptionPane.showOptionDialog(this, 
                "Anda mau minum kopi dengan gula?",
                "Pertanyaan",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                option,
                option[2]);
        
        String respons;
        switch(jwb){
            case 0:String respon = "ini kopi plus gulanya";break;
            case 1:respon = "ok, kopi saja ya";break;
            case 2:respon = "kopi dan krim siap";break;
            default:respon = "kog gak jawab siy?";break;
            
        }
        Object respon = null;
        JOptionPane.showMessageDialog(this, respon);
    }//GEN-LAST:event_btncustomActionPerformed

    private void btnpilihlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpilihlistActionPerformed
        // TODO add your handling code here:
        Object[]jawaban={"Perut"."kaki","hidung"};
        String s=(String)JOptionPane.showInputDialog(this,"Lengkapi kalimat berikut:\n"+
                        "\"Kepala,Pundak,Lutut,...\"",
                "Custom Dialog",
                JOptionPane.PLAIN_MESSAGE,null,jawaban,"Perut");
        
        if((s!=null)&&(s.length()>0)){
            JOptionPane.showMessageDialog(this, 
                    "Kepala,Pundak,Lutut,"+s+"!");
        }
        
    }//GEN-LAST:event_btnpilihlistActionPerformed

    private void btnpilihisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpilihisiActionPerformed
        // TODO add your handling code here:
        String s=(String)JOptionPane.showInputDialog(this, 
                "Lengkapi Kalimat Berikut:\n"+
                        "\"Kepala,Pundak,Lutut,...\"",
                "Custom Dialog",
                JOptionPane.PLAIN_MESSAGE,
                null,
                null,
                "");
        
        if((s!=null)&&(s.length()>0)){
            JOptionPane.showMessageDialog(this, 
                    "Kepala,Pundak,Lutut,"+s+"!");
        }
    }//GEN-LAST:event_btnpilihisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnYN;
    private javax.swing.JButton btnYNC;
    private javax.swing.JButton btncustom;
    private javax.swing.JButton btnerror;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnok;
    private javax.swing.JButton btnpilihisi;
    private javax.swing.JButton btnpilihlist;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
