/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas1;

/**
 *
 * @author ACER
 */
public class Tugas1Design extends javax.swing.JFrame {

    /**
     * Creates new form Tugas1Design
     */
    public Tugas1Design() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        SeksGrup005 = new javax.swing.ButtonGroup();
        lblNamaPegawai005 = new javax.swing.JLabel();
        lblGajiPokok005 = new javax.swing.JLabel();
        lblSeks005 = new javax.swing.JLabel();
        lblStatus005 = new javax.swing.JLabel();
        txtNamaPegawai005 = new javax.swing.JTextField();
        txtGajiPokok005 = new javax.swing.JTextField();
        txtGajiTotal005 = new javax.swing.JTextField();
        txtPasangan005 = new javax.swing.JTextField();
        rbPria005 = new javax.swing.JRadioButton();
        rbWanita005 = new javax.swing.JRadioButton();
        cbMenikah005 = new javax.swing.JCheckBox();
        lblJumlahAnak005 = new javax.swing.JLabel();
        txtJumlahAnak005 = new javax.swing.JTextField();
        lblPasangan005 = new javax.swing.JLabel();
        lblGajiTotal005 = new javax.swing.JLabel();
        btnHitung005 = new javax.swing.JButton();
        btnHapus005 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblNamaPegawai005.setText("Nama Pegawai");

        lblGajiPokok005.setText("Gaji Pokok");

        lblSeks005.setText("Seks");

        lblStatus005.setText("Status");

        txtGajiTotal005.setEditable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, SeksGrup005, org.jdesktop.beansbinding.ELProperty.create("${selection.enabled}"), txtPasangan005, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        SeksGrup005.add(rbPria005);
        rbPria005.setText("Pria");
        rbPria005.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPria005ActionPerformed(evt);
            }
        });

        SeksGrup005.add(rbWanita005);
        rbWanita005.setText("Wanita");
        rbWanita005.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbWanita005ActionPerformed(evt);
            }
        });

        cbMenikah005.setText("Menikah");
        cbMenikah005.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMenikah005ActionPerformed(evt);
            }
        });

        lblJumlahAnak005.setText("Jumlah Anak");

        txtJumlahAnak005.setEnabled(false);

        lblGajiTotal005.setText("Gaji Total");

        btnHitung005.setText("Hitung Gaji Total");
        btnHitung005.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitung005ActionPerformed(evt);
            }
        });

        btnHapus005.setText("Hapus");
        btnHapus005.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus005ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNamaPegawai005)
                            .addGap(18, 18, 18)
                            .addComponent(txtNamaPegawai005, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblGajiPokok005)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rbPria005)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rbWanita005))
                                .addComponent(txtGajiPokok005, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbMenikah005))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnHitung005)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                            .addComponent(btnHapus005))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSeks005)
                                .addComponent(lblStatus005)
                                .addComponent(lblPasangan005, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblGajiTotal005, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(lblJumlahAnak005)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtJumlahAnak005, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                                .addComponent(txtPasangan005)
                                .addComponent(txtGajiTotal005)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaPegawai005)
                    .addComponent(txtNamaPegawai005, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGajiPokok005)
                    .addComponent(txtGajiPokok005, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeks005)
                    .addComponent(rbPria005)
                    .addComponent(rbWanita005))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus005)
                    .addComponent(cbMenikah005))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlahAnak005)
                    .addComponent(txtJumlahAnak005, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPasangan005, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPasangan005))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitung005)
                    .addComponent(btnHapus005))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGajiTotal005, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGajiTotal005)))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbPria005ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPria005ActionPerformed
        if (rbPria005.isSelected()) {
            lblPasangan005.setText("Nama Istri");
        }
            
    }//GEN-LAST:event_rbPria005ActionPerformed

    private void rbWanita005ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbWanita005ActionPerformed
        if (rbWanita005.isSelected()) {
            lblPasangan005.setText("Nama Suami");
        }
    }//GEN-LAST:event_rbWanita005ActionPerformed

    private void cbMenikah005ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMenikah005ActionPerformed
        if (cbMenikah005.isSelected()) {
            txtJumlahAnak005.setEnabled((true));
        } else {
            txtJumlahAnak005.setEnabled((false));
            txtJumlahAnak005.setText("0");
        }
    }//GEN-LAST:event_cbMenikah005ActionPerformed

    private void btnHitung005ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitung005ActionPerformed
                      int gajiPokok = Integer.parseInt(txtGajiPokok005.getText());
                int jumlahAnak = Integer.parseInt(txtJumlahAnak005.getText());
                double gajiTotal;

                if (jumlahAnak >= 3) {
                    gajiTotal = gajiPokok + (gajiPokok * 0.10 * 3);
                } else {
                    gajiTotal = gajiPokok + (gajiPokok * 0.10 * jumlahAnak);
                }

                txtGajiTotal005.setText(String.valueOf(gajiTotal));
            
    }//GEN-LAST:event_btnHitung005ActionPerformed

    private void btnHapus005ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus005ActionPerformed
        txtNamaPegawai005.setText("");
        txtGajiPokok005.setText("");
        SeksGrup005.clearSelection();
        cbMenikah005.setSelected(false);
        lblPasangan005.setText("");
        txtJumlahAnak005.setText("");
        txtPasangan005.setText("");
        txtGajiTotal005.setText("");
    }//GEN-LAST:event_btnHapus005ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup SeksGrup005;
    private javax.swing.JButton btnHapus005;
    private javax.swing.JButton btnHitung005;
    private javax.swing.JCheckBox cbMenikah005;
    private javax.swing.JLabel lblGajiPokok005;
    private javax.swing.JLabel lblGajiTotal005;
    private javax.swing.JLabel lblJumlahAnak005;
    private javax.swing.JLabel lblNamaPegawai005;
    private javax.swing.JLabel lblPasangan005;
    private javax.swing.JLabel lblSeks005;
    private javax.swing.JLabel lblStatus005;
    private javax.swing.JRadioButton rbPria005;
    private javax.swing.JRadioButton rbWanita005;
    private javax.swing.JTextField txtGajiPokok005;
    private javax.swing.JTextField txtGajiTotal005;
    private javax.swing.JTextField txtJumlahAnak005;
    private javax.swing.JTextField txtNamaPegawai005;
    private javax.swing.JTextField txtPasangan005;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
