/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pmodul7;
import javax.swing.*;
import java.io.*;
import javax.swing.filechooser.FileFilter;



/**
 *
 * @author Lenovo
 */
public class fdesign extends javax.swing.JFrame {
     JFileChooser fc; 
     File file;
     boolean fileBaru;
     final String[] EXT = { ".csv" };
     final String[] EXT2 = { ".txt", ".java" };
 }

    /**
     * Creates new form fdesign
     */

public fdesign() {
        initComponents();
this.setTitle("Untitled - NOTES");
fc = new JFileChooser(); fc.addChoosableFileFilter(new jenisFile(EXT)); 
fc.addChoosableFileFilter(new jenisFile(EXT2));
fc.setAcceptAllFileFilterUsed(false);
fileBaru=true;
}


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnnew = new javax.swing.JButton();
        btnopen = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnsaveass = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        editor = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnnew.setText("New");

        btnopen.setText("Open");

        btnsave.setText("Save");

        btnsaveass.setText("Save Ass");

        btnkeluar.setText("Keluar");

        jScrollPane1.setViewportView(editor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnnew)
                        .addGap(41, 41, 41)
                        .addComponent(btnopen)
                        .addGap(34, 34, 34)
                        .addComponent(btnsave)
                        .addGap(50, 50, 50)
                        .addComponent(btnsaveass)
                        .addGap(34, 34, 34)
                        .addComponent(btnkeluar)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnew)
                    .addComponent(btnopen)
                    .addComponent(btnsave)
                    .addComponent(btnsaveass)
                    .addComponent(btnkeluar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fdesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fdesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fdesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fdesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fdesign().setVisible(true);
            }
        });
    }
    private void msg(String pesan) {
JOptionPane.showMessageDialog(this,pesan,"informasi",
JOptionPane.INFORMATION_MESSAGE);
}
    private boolean okToReplace() {
        return(JOptionPane.showConfirmDialog(this,
                "File"+file.getName()+"Sudah Ada\n"+
                "Akan Ditimpa?",
                "Peringatan",JOptionPane.YES_NO_OPTION)==0);
    }
    private void SimpanFile() { 
        PrintWriter pw = null; 
        try {
            pw = new PrintWriter(new BufferedWriter(new FileWriter(file)));
        } catch (IOException e) {
            msg("Gagal Simpan File : '" + file.getName()); 
            return;
        }
        pw.print(editor.getText());
        pw.close();
        
        this.setTitle(file.getName()+" - NOTES" ); 
        fileBaru = false;
}
    class jenisFile extends FileFilter { 
        private String[] s;
        jenisFile(String[] sArg) { 
            s = sArg;
}
        public boolean accept(File fArg) { 
            if (fArg.isDirectory())
                return true;
            for (int i = 0; i < s.length; ++i)
                if (fArg.getName().toLowerCase().indexOf(s[i].toLowerCase()) > 0) 
                    return true;
            
            return false;
}
        public String getDescription()	{ 
            String tmp = "";
            for (int i = 0; i < s.length; ++i) 
                tmp += "*" + s[i] + " ";
            return tmp;
        }
    }

 



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnopen;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsaveass;
    private javax.swing.JEditorPane editor;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

