/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class utsPMP018 extends javax.swing.JFrame {

    /**
     * Creates new form utsPMP018
     */
    public utsPMP018() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAngka1006 = new javax.swing.JLabel();
        lblAngka2006 = new javax.swing.JLabel();
        lblOperator006 = new javax.swing.JLabel();
        lblHasil006 = new javax.swing.JLabel();
        txtAngka1006 = new javax.swing.JTextField();
        txtAngka2006 = new javax.swing.JTextField();
        cbOperator006 = new javax.swing.JComboBox<>();
        txtHasil006 = new javax.swing.JTextField();
        btnHitung006 = new javax.swing.JButton();
        btnClear006 = new javax.swing.JButton();
        btnExit006 = new javax.swing.JButton();
        lblNama006 = new javax.swing.JLabel();
        lblNim006 = new javax.swing.JLabel();
        lblUtspmp006 = new javax.swing.JLabel();
        lblJudul006 = new javax.swing.JLabel();
        lblFoto006 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        lblAngka1006.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblAngka1006.setForeground(new java.awt.Color(255, 255, 255));
        lblAngka1006.setText("Angka 1");
        getContentPane().add(lblAngka1006);
        lblAngka1006.setBounds(200, 170, 52, 15);

        lblAngka2006.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblAngka2006.setForeground(new java.awt.Color(255, 255, 255));
        lblAngka2006.setText("Angka 2");
        getContentPane().add(lblAngka2006);
        lblAngka2006.setBounds(200, 230, 52, 15);

        lblOperator006.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblOperator006.setForeground(new java.awt.Color(255, 255, 255));
        lblOperator006.setText("Operator");
        getContentPane().add(lblOperator006);
        lblOperator006.setBounds(310, 180, 55, 15);

        lblHasil006.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblHasil006.setForeground(new java.awt.Color(255, 255, 255));
        lblHasil006.setText("Hasil");
        getContentPane().add(lblHasil006);
        lblHasil006.setBounds(440, 200, 31, 15);
        getContentPane().add(txtAngka1006);
        txtAngka1006.setBounds(200, 190, 52, 26);
        getContentPane().add(txtAngka2006);
        txtAngka2006.setBounds(200, 250, 52, 26);

        cbOperator006.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        cbOperator006.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+ ( Tambah )", "- ( Kurang )", "x ( Kali )", "/ ( Bagi )" }));
        getContentPane().add(cbOperator006);
        cbOperator006.setBounds(290, 220, 95, 20);

        txtHasil006.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHasil006ActionPerformed(evt);
            }
        });
        getContentPane().add(txtHasil006);
        txtHasil006.setBounds(420, 220, 70, 26);

        btnHitung006.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btnHitung006.setText("Hitung Hasil");
        btnHitung006.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitung006ActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitung006);
        btnHitung006.setBounds(190, 360, 111, 25);

        btnClear006.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btnClear006.setText("Clear");
        btnClear006.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear006ActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear006);
        btnClear006.setBounds(320, 360, 110, 25);

        btnExit006.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btnExit006.setText("Keluar");
        btnExit006.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit006ActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit006);
        btnExit006.setBounds(460, 360, 71, 25);

        lblNama006.setFont(new java.awt.Font("Kozuka Mincho Pr6N M", 0, 12)); // NOI18N
        lblNama006.setForeground(new java.awt.Color(255, 255, 255));
        lblNama006.setText("NAMA : Ramadhani Dava Setyawan");
        getContentPane().add(lblNama006);
        lblNama006.setBounds(270, 10, 230, 30);

        lblNim006.setFont(new java.awt.Font("Kozuka Mincho Pr6N M", 0, 12)); // NOI18N
        lblNim006.setForeground(new java.awt.Color(255, 255, 255));
        lblNim006.setText("NIM : 22144002");
        getContentPane().add(lblNim006);
        lblNim006.setBounds(270, 40, 86, 30);

        lblUtspmp006.setFont(new java.awt.Font("Kozuka Gothic Pr6N M", 0, 12)); // NOI18N
        lblUtspmp006.setForeground(new java.awt.Color(255, 255, 255));
        lblUtspmp006.setText("UTS PMP");
        getContentPane().add(lblUtspmp006);
        lblUtspmp006.setBounds(270, 70, 60, 30);

        lblJudul006.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        lblJudul006.setForeground(new java.awt.Color(204, 204, 255));
        lblJudul006.setText("KALKULATOR");
        getContentPane().add(lblJudul006);
        lblJudul006.setBounds(200, 120, 165, 30);

        lblFoto006.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto006.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Downloads\\12.jpg")); // NOI18N
        getContentPane().add(lblFoto006);
        lblFoto006.setBounds(-510, -280, 1610, 1250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHasil006ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHasil006ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHasil006ActionPerformed

    private void btnHitung006ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitung006ActionPerformed
        int angka1 = Integer.parseInt(txtAngka1006.getText());
        int angka2 = Integer.parseInt(txtAngka2006.getText());
        String operator = cbOperator006.getSelectedItem().toString();
        
        int hasil;
        if (operator == "+ ( Tambah )"){
            hasil = angka1 + angka2;

        }else if(operator == "- ( Kurang )"){
            hasil = angka1 - angka2;

        }else if(operator == "x ( Kali )"){
            hasil = angka1 * angka2;
        }else {hasil = angka1 / angka2;
    }                        
       txtHasil006.setText(String.valueOf(hasil)); 
    }//GEN-LAST:event_btnHitung006ActionPerformed

    private void btnClear006ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear006ActionPerformed
        // TODO add your handling code here:
        txtAngka1006.setText (" ");
        txtAngka2006.setText (" ");
        txtHasil006.setText (" ");
    }//GEN-LAST:event_btnClear006ActionPerformed

    private void btnExit006ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit006ActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_btnExit006ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utsPMP018.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utsPMP018.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utsPMP018.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utsPMP018.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new utsPMP018().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear006;
    private javax.swing.JButton btnExit006;
    private javax.swing.JButton btnHitung006;
    private javax.swing.JComboBox<String> cbOperator006;
    private javax.swing.JLabel lblAngka1006;
    private javax.swing.JLabel lblAngka2006;
    private javax.swing.JLabel lblFoto006;
    private javax.swing.JLabel lblHasil006;
    private javax.swing.JLabel lblJudul006;
    private javax.swing.JLabel lblNama006;
    private javax.swing.JLabel lblNim006;
    private javax.swing.JLabel lblOperator006;
    private javax.swing.JLabel lblUtspmp006;
    private javax.swing.JTextField txtAngka1006;
    private javax.swing.JTextField txtAngka2006;
    private javax.swing.JTextField txtHasil006;
    // End of variables declaration//GEN-END:variables
}
